server:
    port: 8005
    servlet:
        session:
            cookie:
                secure: false
                http-only: true
                same-site: none
spring:
    application:
        name: user
    datasource:
        url: jdbc:mysql://localhost:3307/tickup
        driver-class-name: com.mysql.cj.jdbc.Driver
        username: root
        password: root123
    jpa:
        hibernate:
            ddl-auto: update
        show-sql: true
    kafka:
        producer:
            value-serializer: org.springframework.kafka.support.serializer.JsonSerializer
#        properties:
#            hibernate:
#                format_sql: true
#                dialect: org.hibernate.dialect.MySQLDialect
logging:
    level:
        org:
            springframework:
                security: DEBUG