name: Docker Image CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    # 1. 코드 체크아웃
    - name: Checkout code
      uses: actions/checkout@v4

    # 2. Java 환경 설정
    - name: Set up JDK 17
      uses: actions/setup-java@v4
      with:
        java-version: '17'
        distribution: 'temurin' # Java 배포판 선택 (예: AdoptOpenJDK)

    # 3. Gradle 캐시 설정
    - name: Cache Gradle dependencies
      uses: actions/cache@v4
      with:
        path: ~/.gradle/caches
        key: gradle-${{ hashFiles('**/*.gradle*', '**/gradle-wrapper.properties') }}
        restore-keys: gradle-

    # 4. Docker 로그인을 위한 환경 변수 설정
    - name: Log in to Docker Hub
      uses: docker/login-action@v3
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}

    # 5. Gradle로 도커 이미지 생성
    - name: Build Docker Image using bootBuildImage
      run: ./gradlew bootBuildImage --imageName=gksderrick/tickup-front:latest

    # 6. Docker Hub에 이미지 푸시
    - name: Push Docker Image
      run: docker push gksderrick/tickup-front:latest
